# Generated by Django 5.2.17 on 2026-09-10 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailingmessage',
            name='delivery_attempts',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='mailingmessage',
            name='delivery_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed')], db_index=True, default='pending', max_length=16),
        ),
        migrations.AddField(
            model_name='mailingmessage',
            name='last_delivery_error',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='mailingmessage',
            name='sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name='mailingmessage',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('delivery_status', 'sent'), ('sent_at__isnull', False)), models.Q(('delivery_status__in', ('pending', 'failed')), ('sent_at__isnull', True)), _connector='OR'), name='mailing_sent_status_matches_timestamp'),
        ),
    ]
